[en]
  languageName = "English"
  languageCode = "en"
  weight = 2
  title = "ByteWing"
  [en.params]
    tagline = ""

[zh-CN]
  languageName = "中文"
  languageCode = "zh-CN"
  weight = 1
  title = "ByteWing"
  [zh-CN.params]
    tagline = ""