# --- 最终配置文件 ---

# 1. 基础信息 (请修改为你自己的)
baseURL = "https://bytewing233.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"

theme = "chirpy"

# 3. 启用 Git Info (我们稍后会创建 commit)
enableGitInfo = true
hasCJKLanguage = true # 支持中文搜索

# 7. 其他高级配置 (保持不变即可)
[outputs]
  home = ["HTML", "RSS", "JSON"] # 为搜索功能生成 JSON
[taxonomies]
  category = "categories"
  tag = "tags"
[markup.goldmark.renderer]
  unsafe = true # 允许在 Markdown 中使用原始 HTML
[markup.tableOfContents]
  startLevel = 2
  endLevel = 4

# 主导航菜单配置
# 暂时隐藏首页
# [[menu.main]]
#   name = "首页"
#   url = "/"
#   weight = 1
#   pre = "fa-home"

# 主菜单配置
[[menu.main]]
  name = "CS/AI"
  url = "/cs-ai/"
  weight = 2
  pre = "fa-microchip"

[[menu.main]]
  name = "Arts & Humanities"
  url = "/literature/"
  weight = 3
  pre = "fa-feather-alt"

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 4
  pre = "fa-stream"

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 5
  pre = "fa-tags"

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 6
  pre = "fa-archive"

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 7
  pre = "fa-info-circle"

